server {
    listen 80;
    server_name timurkud.info;
    return 301 https://$host$request_uri;
}

server {
    listen 443 ssl;
    server_name timurkud.info;

    ssl_certificate /etc/letsencrypt/live/timurkud.info/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/timurkud.info/privkey.pem;

    client_max_body_size 20M;

    location /kaspi {
        return 301 /kaspi/;
    }

    location /kaspi/ {
        proxy_pass http://app:8000/;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
    }

    location / {
        root /portfolio;
        try_files $uri $uri/ /index.html;
    }
}
